ARG JUPYTERHUB_VERSION=3.0.2
FROM jupyterhub/k8s-hub:$JUPYTERHUB_VERSION
ARG GLOBAL_PASSWORD

# Add template override directory and copy our example
# Replace the default
USER root
RUN mv /usr/local/share/jupyterhub/templates/login.html /usr/local/share/jupyterhub/templates/_login.html
COPY login.html /usr/local/share/jupyterhub/templates/login.html
USER jovyan