apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  region: us-east-2
  name: hpsf-flux
  
availabilityZones: ["us-east-2b", "us-east-2c"]
managedNodeGroups:
  - name: workers
    availabilityZones: ["us-east-2b"]
    instanceType: hpc6a.48xlarge
    volumeSize: 150
    volumeType: gp2
    minSize: 2
    maxSize: 2
    efaEnabled: true
    placement:
      groupName: performance-study
