FROM nvcr.io/nvidia/pytorch:24.02-py3
RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    wget \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /code
COPY ./flux-operator/requirements.txt /code/requirements.txt
RUN pip install mcp-serve
RUN git clone -b fix-database-arg https://github.com/converged-computing/fractale /code/fractale && python3 -m pip install -e /code/fractale[all]
RUN pip install sqlalchemy
RUN git clone https://github.com/converged-computing/flux-mcp /code/flux-mcp && python3 -m pip install -e /code/flux-mcp[all]
RUN git clone https://github.com/converged-computing/hpc-mcp /code/hpc-mcp && python3 -m pip install -e /code/hpc-mcp[all]
RUN git clone -b tweak-flux-operator https://github.com/converged-computing/fractale-agents /code/fractale-agents && python3 -m pip install -e /code/fractale-agents[all]
COPY ./flux-operator/distributed_flux.py /code/distributed_flux.py
COPY ./flux-operator/distributed_flux_hello_world.py /code/distributed_flux_hello_world.py
COPY ./flux-operator/mcpserver.yaml /code/mcpserver.yaml
ENV LD_LIBRARY_PATH=/opt/hpcx/ompi/lib:/opt/hpcx/mxm/lib:/opt/hpcx/ucx/lib:$LD_LIBRARY_PATH
ENV PATH=/opt/hpcx/ompi/bin:$PATH
ENV SHELL=/usr/bin/bash
