apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: pytorch
spec:
  size: 2
  flux:
    container:
      image: ghcr.io/converged-computing/flux-view-ubuntu:tag-jammy
  containers:
    - image: vanessa/hpsf-flux:2026-flux-operator-pytorch-11
      launcher: true
      command: mcpserver start --port 8089 --host 0.0.0.0 -t http --config /code/mcpserver.yaml
      environment:
        FI_PROVIDER: "efa"
        FI_EFA_FORK_SAFE: "1"
      volumes:
        shared-memory:
          emptyDir: true
          emptyDirMedium: "memory"
      resources:
        limits:
          vpc.amazonaws.com/efa: 1
        requests:
          vpc.amazonaws.com/efa: 1
