FROM fluxrm/flux-sched:jammy

# Based off of https://github.com/jupyterhub/zero-to-jupyterhub-k8s/tree/main/images/singleuser-sample
# Local usage
# docker run -p 8888:8888 -v $(pwd):/home/jovyan/work test

USER root

ENV NB_USER=jovyan \
    NB_UID=1000 \
    HOME=/home/jovyan

RUN adduser \
    --disabled-password \
    --gecos "Default user" \
    --uid ${NB_UID} \
    --home ${HOME} \
    --force-badname \
    ${NB_USER}

RUN apt-get update \
    # && apt-get upgrade -y \
    && apt-get install -y --no-install-recommends \
    gcc-10 \
    g++-10 \
    ca-certificates \
    dnsutils \
    iputils-ping \
    python3 \
    python3-dev \
    python3-pip \
    python3-venv \
    openmpi-bin \
    openmpi-common \
    libopenmpi-dev \
    liblz4-dev \
    tini \
    nodejs \
    # requirement for nbgitpuller
    git \
    && rm -rf /var/lib/apt/lists/*

COPY ./requirements_venv.txt ./requirements_venv.txt
RUN python3 -m pip install -r requirements_venv.txt

COPY ./requirements.txt ./requirements.txt
RUN python3 -m pip install -r requirements.txt && \
    python3 -m pip install ipython==7.34.0  && \
    python3 -m IPython kernel install

# This adds the flux-tree command, which is provided in flux-sched source
# but not installed alongside production flux-core
COPY ./flux-tree/* /usr/libexec/flux/cmd/
RUN chmod +x /usr/libexec/flux/cmd/flux-tree*

RUN wget https://nodejs.org/dist/v20.15.0/node-v20.15.0-linux-x64.tar.xz && \
    apt-get update && apt-get install -y xz-utils && rm -rf /var/lib/apt/lists/* && \
    xz -d -v node-v20.15.0-linux-x64.tar.xz && \
    tar -C /usr/local --strip-components=1 -xvf node-v20.15.0-linux-x64.tar

# This customizes the launcher UI
# https://jupyter-app-launcher.readthedocs.io/en/latest/usage.html
RUN python3 -m pip install jupyter_app_launcher && \
    python3 -m pip install --upgrade jupyter-server && \
    python3 -m pip install jupyter-launcher-shortcuts && \
    mkdir -p /usr/local/share/jupyter/lab/jupyter_app_launcher

COPY ./tutorial /home/jovyan/
COPY ./docker/jupyter-launcher.yaml /usr/local/share/jupyter/lab/jupyter_app_launcher/jp_app_launcher.yaml
ENV JUPYTER_APP_LAUNCHER_PATH=/usr/local/share/jupyter/lab/jupyter_app_launcher/

# Give jovyan user permissions to tutorial materials
RUN chmod -R 777 ~/ /home/jovyan

WORKDIR $HOME
# Flux assets in the tutorial/ directory were moved to tutorial/img/
# this shouldn't be a problem for the next command but making a note in case
COPY ./docker/flux-icon.png $HOME/flux-icon.png

# note that previous examples are added via git volume in config.yaml
ENV SHELL=/usr/bin/bash
ENV FLUX_URI_RESOLVE_LOCAL=t

EXPOSE 8888
ENTRYPOINT ["tini", "--"]

# This is for JupyterHub
COPY ./docker/entrypoint.sh /entrypoint.sh

# This is for a local start
COPY ./docker/start.sh /start.sh

RUN mkdir -p $HOME/.local/share && \
    chmod 777 $HOME/.local/share

USER ${NB_USER}

CMD ["flux", "start", "--test-size=4", "jupyter", "lab"]
